### ISSUE TITLE
Device Operations in QT app

### ISSUE THREAD

**Issue by willwade** [AceCentre/RelayKeys#81]
"I can't get the device operations to work (even when connected to a tablet and working it lists no devices).

I have issues getting my connected target devices (android phone and an old Windows tablet) to reconnect. I can pair up and RelayKeys works fine, then turn off or take it out of range. When trying to re-establish connection later I have to force forget pairing and re-pair. I assume this is a behaviour of the targets but  it happens on both. I have some BT mice and keyboards that reconnect smoothly so maybe it's a problem with the BLE Friend?"

**Comment by joedevsys** [comment]
This Issue is actually two issues (1) "I can't get the device operations to work" in QT app used with a BLE Friend, and (2)  Auto-reconnection issues on the target device (which could either be Friend related or may be target device related). I have opened another Issue for the latter.

Regarding (1) These device operations aren't going to be usable on the BLE Friend. You have created custom AT commands to manage the connection which are interpreted in the Arduino to drive the Bluefruit nRF52 library. These custom AT commands don't exist on the BLE Friend and it doesn't appear to have other AT commands that would be needed for managing connections. (It might be possible to dig deep into  GAP/GATT but I'm not convinced, and this would all have to be handled in the server service which seems messy).

**Comment by joedevsys** [comment]
Relay Keys 1.7, i13 communication aid, Bluefruit BLE Friend paired to Android phone. Reconnection seems reasonably reliable now. Can take phone out of range or reboot either device and it reconnects successfully. The one situation that requires the daemon service to be restarted is if the dongle is unplugged and plugged back in.
